### PR TITLE
added types for int8, int16, Time for mysql driver

### PR DESCRIPTION
**Pull request by crisward**
I get an error on mysql without these.
Related to this - https://github.com/crystal-lang/crystal-mysql/pull/15

### CODE REVIEW

**Comment by bcardiff** [comment]
Time will arrive to DB::Any. I am a bit hesitant regarding Int8/Int16.

Int8/Int16 and specially UInt8/16 are mainly for interfacing with C.
Some dbs  support even unsigned, but I am not they all should be added here.

@crisward I am not following why without this PR you get errors in mysql. Can you share some dump/log?

**Comment by crisward** [comment]
Error here - https://gist.github.com/crisward/5b228395b8b7e14d7669d59ed9b32faf

**Comment by bcardiff** [comment]
@crisward Int8/16 stories should be fixed at crystal-mysql@master. check crystal-lang/crystal-mysql#18 . 

I though this would been covered by [this spec](https://github.com/crystal-lang/crystal-mysql/blob/a1db0df999cd6247b946745893ed98979cc113a9/spec/driver_spec.cr#L99-L114) but the case without unions in the exec args didn't raise the issue you point in the error.

If that is ok, then we could close this issue since mysql can extend the type to be used outside DB::Any.

**Comment by crisward** [comment]
Thanks, that fixes it. I'll close.

**Pull request closed without merging**
