### PR TITLE
making exception error string a proper error class.

### LINKED ISSUE #120: A better error for "no results"
Right now if your query doesn't return anything, an exception is raised saying [no results](https://github.com/crystal-lang/crystal-db/blob/master/src/db/statement.cr#L18).

I'd like to propose this become a special class like `raise NoResultsException.new("no results")`. This would allow libraries that wrap this to catch on that error specifically to handle things specialized for that library.

### PR DESCRIPTION
**Pull request by jwoertink**
Fixes #120

I was going to write a spec for it, but the specs in this are sort of complicated, and I wasn't sure how to test that the scalar raises an exception.

### CODE REVIEW

**Comment by straight-shoota** [comment]
How about `SELECT LIMIT 0`?

**Comment by jwoertink** [comment]
I tried doing this:

```crystal
    with_dummy do |db|
      expect_raises DB::NoResultsError do
        db.scalar "SELECT LIMIT 0"
      end
    end
```

but it never raises an exception.

**Comment by jwoertink** [comment]
ah, nevermind, I was using the wrong thing.

**Comment by jwoertink** [comment]
Hey, just wanted to ping this. If anyone has a second to look over it. Thanks!

**Comment by straight-shoota** [comment]
Thanks @jwoertink

**Pull request merged**
